### ISSUE TITLE
Lilbrary Gestion : See Game

### ISSUE THREAD

**Issue by Heffiros** [PLI-Octavia/Octavia#7]
Create a page to see all available game.

Get all game aff on the page : 

 - If the game is activated : NOM du jeu  + Miniature + bouton desactiver/activer (look bootstrap-swicth) it is cool) + button to aff details game page.
- If the game is desactived : NOM du jeu + miniature grise + bouton desactiver/activer + + button to aff details game page + little message to say is desactivated

**Comment by vendethiel** [comment]
done in 24a622db6ddc0cacb858ad3c8d525e5937c77e07
